---
title: "COMPSCIX 415.2 Data Import in Class 4"
author: "Rachel Hollowgrass"
date: "2/20/2018"
output:
 html_document:
  self_contained: true
---

```{r, warning = FALSE, message = FALSE}
library(rvest)
library(nycflights13)
library(tidyverse)
```


What is the number and proportion of cancelled flights on Febuary 20th, 2013? Use summarize along with the sum and mean of logical values in your final answer.

```{r}
file_path <- '../data/flights.csv'
csv_data <- read_csv(file_path)
```

```{r}
contact_movie <- read_html("http://www.imdb.com/title/tt0118884/")
class(contact_movie)
  
contact_movie %>%
  html_nodes("#titleCast .itemprop span") %>%
  html_text()
```


```{r}
data(iris)
iris <- as.data.frame(iris)
iris
iris <- as_tibble(iris)
iris
```
```{r}
?flights
```

```{r}
file_path <- '../data/flights.csv'
csv_data <- read_csv(file_path)
```

  
```{r}
write_delim(csv_data, delim = ';', path = '../data/flights_semi.csv')
```

  
```{r}
write_tsv(csv_data, path = '../data/flights_tab.tsv')
```

```{r}
saveRDS(csv_data, file = "../data/flights_rds.rds")
```

