---
title: "COMPSCIX 415.2 Work During Class 8"
author: "Rachel Hollowgrass"
date: "3/20/2018"
output:
 html_document:
  self_contained: true
---

```{r, warning = FALSE, message = FALSE}
library(ISLR)
library(tidyverse)
library(broom)
```

```{r}
logit_mod_1 <- glm(default ~ balance, data = Default, 
                 family = 'binomial')
tidy(logit_mod_1)
```


```{r}
logit_mod_2 <- glm(default ~ student, data = Default, 
                 family = 'binomial')
tidy(logit_mod_2)
```

```{r}
library(rpart)

Heart <- read_csv('../data/heart.csv')
# The dot means "all features"
tree_mod0 <- rpart(AHD ~ ., data = Heart)
```

```{r}
library(partykit)
plot(as.party(tree_mod0))
```

```{r}

tree_mod0 <- rpart(AHD ~ ., data = Heart)
preds <- predict(tree_mod0, newdata = Heart)
head(preds)

Heart <- Heart %>% mutate(preds_prob = preds[, 2]) %>% 
  mutate(preds_cat = case_when(preds_prob < .5 ~ 'No',
                               preds_prob >= .5 ~ 'Yes'))
Heart %>% count(preds_cat)


library(ROCR)
pred_obj <- prediction(predictions = Heart$preds_prob, 
    labels = Heart$AHD)

roc <- performance(prediction.obj = pred_obj,
                   measure = 'tpr', x.measure = 'fpr')
plot(roc)
```